2 feature 2 interactive scheduler
CSC207-2022F-UofT/course-project-productive-potato-sloth pull request #31
Opened 2022-11-29 00:37 UTC by nitvishn

I've finished up the ScheduleEvent use case to functional completion -- the commit messages provide a good picture. Some refactoring needs to happen to clean up code, this is primarily in the interactor. Simplifications will be made once more User methods are implemented.

2022-11-29 03:38 UTC, ConverseScholar requested changes

2022-11-29 03:38 UTC, ConverseScholar commented on gradlew.bat
> +@rem
add all these gradle files to gitignore then commit again

2022-12-03 18:01 UTC, paridhi26 requested changes
I think it is better to have setupScheduleEvent from the Main class in a separate class of it's own. Something like SchedulerMainScreen or SchedulerEventView. It is better to not clutter Main class, becuase if we all add our display methods (that setup the respective screens our features) to the Main class, it will be too big. This leads to large class code smell, which should be avoided.

2022-12-03 23:33 UTC, Dawei-He2002 submitted a review, later dismissed

2022-12-03 23:37 UTC, 1StevenJiang1 submitted a review, later dismissed

2022-12-03 23:40 UTC, ConverseScholar commented on src/main/java/screens/CheckboxListCellRenderer.java
> +}
beautiful implementation

2022-12-03 23:41 UTC, paridhi26 submitted a review, later dismissed

2022-12-03 23:41 UTC, ConverseScholar commented on src/main/java/screens/ScheduleEvent/ScheduleEventMainFrame.java
> +        cardLayout.show(screens, "register");
change name

2022-12-03 23:44 UTC, ConverseScholar commented on src/main/java/useCases/ScheduleEvent/ScheduleEventInteractor.java
> +    }
great use of checking different cases. good implementation of clean architecture

2022-12-03 23:45 UTC, ConverseScholar approved these changes, later dismissed

2022-12-04 01:56 UTC, kldtntg submitted a review, later dismissed

2022-12-04 01:58 UTC, ConverseScholar commented on src/test/java/usecases/ScheduleEventTest.java
> +}
thanks so much for fixing our project, Vishnu. you are our 207 god

2022-12-04 01:59 UTC, ConverseScholar commented on src/test/java/usecases/ScheduleEventTest.java
> +}
now we know not to mess with github

2022-12-04 01:59 UTC, ConverseScholar submitted a review, later dismissed

2022-12-04 02:02 UTC, ConverseScholar commented on src/test/java/usecases/ScheduleEventTest.java
> +}
still thank you despite committing when you should've waited

2022-12-04 02:02 UTC, ConverseScholar submitted a review, later dismissed

2022-12-04 02:03 UTC, kldtntg submitted a review, later dismissed

2022-12-04 02:56 UTC, 1StevenJiang1 approved these changes, later dismissed

2022-12-04 22:36 UTC, 1StevenJiang1 approved these changes, later dismissed

2022-12-04 22:39 UTC, ConverseScholar commented on src/test/java/usecases/ScheduleEventTest.java
> +}
this is amazing. thanks so much Vishnu

2022-12-04 22:39 UTC, ConverseScholar submitted a review, later dismissed

2022-12-04 23:25 UTC, chazzybearr commented
I fixed the merge conflict in Task and User and that seemed to create more problems (?)

2022-12-04 23:41 UTC, chazzybearr approved these changes

2022-12-04 23:43 UTC, ConverseScholar commented on src/test/java/usecases/ScheduleEventTest.java
> +}
Leon stop making me review this one pull request 5 times. Thank you <3

2022-12-04 23:43 UTC, ConverseScholar approved these changes

2022-12-04 23:44 UTC, chazzybearr commented
I'm so sorry Chhavi

2022-12-04 23:45 UTC, ConverseScholar commented
Thanks Leon

2022-12-04 23:45 UTC, ConverseScholar commented
You are not forgiven

2022-12-04 23:46 UTC, chazzybearr commented
I'm literally crying right now

2022-12-04 23:49 UTC, ConverseScholar commented
The worst is not over. Stay strong, Productive Potato Sloth <3

2022-12-05 00:55 UTC, 1StevenJiang1 approved these changes

2022-12-05 01:01 UTC, merged